[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.22", features = ["derive"] }
enum-iterator = "2.1.0"
graphrs = "0.11.5"
itertools = "0.13.0"
patharg = "0.4.0"
regex = "1.11.1"

[dev-dependencies]
indoc = "2.0.5"
